@host = http://localhost:5251
@email = gargas.w@gmail.com
@newEmail = vasav52595@anawebs.com
@username = testuser1
@password = Secret123!
@taskId = 4f380316-bf96-439d-8f90-b3794ff14e61

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3NWMzNTAzZS00MzFiLTRmMjAtYThjNi1kNGFkZjAxNDU2NTEiLCJqdGkiOiJhNmUwZjhkNjRhZmM0M2IzOWEzMzhmM2Q3YjE1MTExMSIsInVuaXF1ZV9uYW1lIjoiNzVjMzUwM2UtNDMxYi00ZjIwLWE4YzYtZDRhZGYwMTQ1NjUxIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiVXNlciIsIm5iZiI6MTc3ODY3MjEwNSwiZXhwIjoxNzc4Njc1NzA1LCJpc3MiOiJ0b2RvIiwiYXVkIjoidG9kby1hcGkifQ.ohQNxhjLsxPCrr4iGjOt9slQU04Y3lmBPN0dFtXMD80
@adminToken = WSTAW_ADMIN_ACCESS_TOKEN

### Sign up - default role (User)
POST {{host}}/Auth/sign-up
Content-Type: application/json
Accept: application/json

{
  "userId": "00000000-0000-0000-0000-000000000000",
  "email": "gargas.w@gmail.com",
  "username": "xxx",
  "password": "Secret123!",
  "fullName": "xxx",
  "role": null
}

### Confirm email from link (token z maila)
@confirmToken = paste-token-from-email-link
GET {{host}}/Auth/confirm-email?token={{confirmToken}}
Accept: application/json

### Confirm email (POST)
POST {{host}}/Auth/confirm-email
Content-Type: application/json
Accept: application/json

{
  "token": "{{confirmToken}}"
}

### Sign in
POST {{host}}/Auth/sign-in
Content-Type: application/json
Accept: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Request email change (sends confirmation email)
PATCH {{host}}/Profile/profile/changeEmail
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "newEmail": "{{newEmail}}"
}

### Confirm changed email from link (token from email)
@changeEmailConfirmToken = paste-email-change-token-from-mail
GET {{host}}/Auth/confirm-email?token={{changeEmailConfirmToken}}
Accept: application/json

### Sign in with new email (after confirmation)
POST {{host}}/Auth/sign-in
Content-Type: application/json
Accept: application/json

{
  "email": "{{newEmail}}",
  "password": "{{password}}"
}

### Get all users
GET {{host}}/Users/all
Accept: application/json

### Get user by id (wklej id z poprzedniego wyniku /Users/all)
@userId = 3c53f28c-5865-41df-9d40-b6f1d2771083
GET {{host}}/Users/{{userId}}
Accept: application/json

### Get user with tasks by id
GET {{host}}/Users/{{userId}}/tasks
Accept: application/json

### Add task for existing verified user
POST {{host}}/Tasks/addTask
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
  "name": "Task testowy",
  "description": "Dodany dla aktualnie zalogowanego użytkownika"
}

### Verify task is visible for user
GET {{host}}/Users/{{userId}}/tasks
Accept: application/json
Authorization: Bearer {{token}}

### Admin adds task for selected user
POST {{host}}/users/{{userId}}/tasks
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{adminToken}}

{
  "name": "Task dodany przez admina",
  "description": "Dodany endpointem admin"
}

### Verify user tasks after admin add
GET {{host}}/Users/{{userId}}/tasks
Accept: application/json
Authorization: Bearer {{adminToken}}


### Get single task by id (authorized user)
GET {{host}}/Tasks/{{taskId}}
Accept: application/json
Authorization: Bearer {{token}}
